title:             李威威的博客
email:             liweiwei1419@gmail.com
description:       快乐生活每一天
author:            liweiwei
baseurl:           "/blog"
url:               "http://liweiwei1419.github.io/blog"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   liweiwei1419
#facebook_username: StartBootstrap

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
